services:
  db:
    image: mariadb:11.8
    restart: unless-stopped
    environment:
      MARIADB_ROOT_PASSWORD: secret
      MARIADB_DATABASE: alexandria
      MARIADB_USER: alexuser
      MARIADB_PASSWORD: alexpass
    ports:
      - "${MARIADB_HOST_PORT:-3306}:3306"
    volumes:
      - db_data:/var/lib/mysql
      - ./alexandria_tables.sql:/docker-entrypoint-initdb.d/1-structure.sql:ro
    healthcheck:
      test: ["CMD", "healthcheck.sh", "--connect", "--innodb_initialized"]
      start_period: 10s
      interval: 10s
      timeout: 5s
      retries: 3

  web:
    build: .
    depends_on:
      db:
        condition: service_healthy
    environment:
      DB_HOST: db
      DB_USER: alexuser
      DB_PASS: alexpass
      DB_NAME: alexandria
      DB_PORT: "${DB_PORT:-3306}"
    ports:
      - "8080:80"
    restart: unless-stopped
    volumes:
      # Mount the www directory for live development
      - ./www:/var/www/html
      # Mount only the Smarty templates for live template development
      - ./smarty/templates:/var/www/smarty/templates
      # Mount includes so social/login configs are available during development
      - ./includes:/var/www/includes:ro

volumes:
  db_data:
